In [1]:
import os, sys
from tqdm import tqdm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile
import shutil
import collections
from pathlib import Path

In [2]:
import warnings
warnings.filterwarnings('ignore')

### Loading packages

In [3]:
import sys
from pathlib import Path

here_path = Path().resolve()
repo_path = here_path.parents[1]
sys.path.append(str(repo_path))

In [4]:
from py.utils import verifyDir, verifyFile, verifyType

In [5]:
from py.config import Config

cfg = Config()

np.random.seed(cfg.RANDOM_STATE)
cfg.DATA_PATH, cfg.MODEL_PATH

('/media/felipe/DATA21/datasets/', '/media/felipe/DATA21/models/')

In [6]:
QSCORE_PATH=f"{cfg.DATA_PATH}pp1/Qscores/"
IMAGES_PATH = f"{cfg.DATA_PATH}pp1/images/"
FEATURES_PATH = f"{cfg.MODEL_PATH}pp1/urbanvgg/{cfg.YEAR_STUDIED}/features/"
MODEL_PATH = f"{cfg.MODEL_PATH}pp1/urbanvgg/{cfg.YEAR_STUDIED}/linear/"

In [7]:
verifyDir(MODEL_PATH)

### Loading data

In [8]:
%%time
import pickle

with open(f"{FEATURES_PATH}features.pkl", "rb") as f:
    features_dict = pickle.load(f)
del features_dict["sift"]

CPU times: user 384 ms, sys: 763 ms, total: 1.15 s
Wall time: 1.15 s

In [9]:
features_df = pd.DataFrame(data=features_dict)
features_df["image_id"] = features_df["image_id"].apply(str)
features_df

,image_id,image_path,gist,fisher
0,4340,/media/felipe/DATA21/datasets/pp1/images/2013/...,"[0.0003824000286834025, -0.0007359776813821125...","[0.017448671731241084, 0.012729228954872664, -..."
1,4196,/media/felipe/DATA21/datasets/pp1/images/2013/...,"[0.001627001220609783, -0.0008733123710065402,...","[0.016221390405270035, 0.013565037150411064, -..."
2,4189,/media/felipe/DATA21/datasets/pp1/images/2013/...,"[0.0008589332392135187, 0.0003564103993083071,...","[-0.01061592723593974, 0.004127063606034159, 0..."
3,3527,/media/felipe/DATA21/datasets/pp1/images/2013/...,"[0.0006579555142264311, 0.0031672864407288875,...","[0.016556280387538033, 0.009603589075775862, -..."
4,4727,/media/felipe/DATA21/datasets/pp1/images/2013/...,"[-7.674301068467588e-05, -0.000699356728799707...","[0.01363824240343455, 0.015022983806787142, 0...."
...,...,...,...,...
2451,3520,/media/felipe/DATA21/datasets/pp1/images/2013/...,"[0.0006566648728943774, 0.0005313509778179662,...","[-0.005612167072383386, 0.007712304538649707, ..."
2452,4725,/media/felipe/DATA21/datasets/pp1/images/2013/...,"[0.000775623296596168, 0.0005924976152852323, ...","[-0.006195889332312467, 0.00360256644672655, 0..."
2453,4904,/media/felipe/DATA21/datasets/pp1/images/2013/...,"[0.0011134001391010992, -0.000379057415558252,...","[-0.00943606031759845, -0.00489945641802752, -..."
2454,4162,/media/felipe/DATA21/datasets/pp1/images/2013/...,"[0.0007136718174012811, 0.0005144085981259512,...","[-0.011163263475166049, -0.00805429512100221, ..."
2455,4074,/media/felipe/DATA21/datasets/pp1/images/2013/...,"[0.0005207238625805728, 0.00044315589572695743...","[-0.01031312623363287, -0.012640398840686582, ..."

In [10]:
%%time
data_df = pd.read_csv(f"{QSCORE_PATH}scores.csv", sep=";", low_memory=False)
data_df["image_path"] = f"{IMAGES_PATH}{cfg.YEAR_STUDIED}/" + data_df["image_path"]
data_df["image_id"] = data_df["image_id"].apply(str)
data_df.sort_values(by=[cfg.PERCEPTION_METRIC], ascending=False, inplace=True)
data_df

CPU times: user 18 ms, sys: 2.01 ms, total: 20 ms
Wall time: 19.4 ms

,image_id,safety,safety_err,uniquely,uniquely_err,wealthy,wealthy_err,lat,long,city,Heading,Pitch,image_path,continent,country
1130,4340,8.350865,0.621166,4.528970,0.668607,7.245005,0.577930,42.3354,-71.1407,Boston,85.0,-3.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA
891,4196,8.327766,0.556107,5.022737,0.833578,7.498167,0.656081,40.6780,-73.9703,New York,329.0,1.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA
1117,4189,8.327241,0.602638,7.108436,0.738665,7.594670,0.634063,40.6948,-73.9712,New York,33.0,11.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA
370,3527,8.245561,0.456143,7.760654,0.836348,8.142057,0.693277,40.6795,-73.9731,New York,324.0,3.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA
303,4727,8.236001,0.510115,7.601103,0.631219,9.164302,0.627555,42.3417,-71.0792,Boston,105.0,6.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,3520,0.762055,0.460119,2.167670,0.572258,1.766562,0.470312,40.6307,-74.0047,New York,346.0,-1.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA
301,4725,0.560845,0.582538,2.764210,0.757413,0.966390,0.523086,42.3812,-71.0890,Boston,15.0,-3.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA
2276,4904,0.517857,0.527475,2.454082,0.681900,1.576652,0.381375,42.3888,-71.0872,Boston,8.0,-2.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA
1188,4162,0.465477,0.462276,1.970528,0.661715,1.627882,0.514609,40.7096,-73.9278,New York,28.0,4.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA
2152,4074,0.211544,0.574673,2.742072,0.794404,1.388283,0.559084,40.7035,-73.9447,New York,214.0,-4.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA

In [11]:
data_df = pd.merge(data_df, features_df, how="inner", on=["image_id", "image_path"])
data_df

,image_id,safety,safety_err,uniquely,uniquely_err,wealthy,wealthy_err,lat,long,city,Heading,Pitch,image_path,continent,country,gist,fisher
0,4340,8.350865,0.621166,4.528970,0.668607,7.245005,0.577930,42.3354,-71.1407,Boston,85.0,-3.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA,"[0.0003824000286834025, -0.0007359776813821125...","[0.017448671731241084, 0.012729228954872664, -..."
1,4196,8.327766,0.556107,5.022737,0.833578,7.498167,0.656081,40.6780,-73.9703,New York,329.0,1.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA,"[0.001627001220609783, -0.0008733123710065402,...","[0.016221390405270035, 0.013565037150411064, -..."
2,4189,8.327241,0.602638,7.108436,0.738665,7.594670,0.634063,40.6948,-73.9712,New York,33.0,11.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA,"[0.0008589332392135187, 0.0003564103993083071,...","[-0.01061592723593974, 0.004127063606034159, 0..."
3,3527,8.245561,0.456143,7.760654,0.836348,8.142057,0.693277,40.6795,-73.9731,New York,324.0,3.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA,"[0.0006579555142264311, 0.0031672864407288875,...","[0.016556280387538033, 0.009603589075775862, -..."
4,4727,8.236001,0.510115,7.601103,0.631219,9.164302,0.627555,42.3417,-71.0792,Boston,105.0,6.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA,"[-7.674301068467588e-05, -0.000699356728799707...","[0.01363824240343455, 0.015022983806787142, 0...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2451,3520,0.762055,0.460119,2.167670,0.572258,1.766562,0.470312,40.6307,-74.0047,New York,346.0,-1.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA,"[0.0006566648728943774, 0.0005313509778179662,...","[-0.005612167072383386, 0.007712304538649707, ..."
2452,4725,0.560845,0.582538,2.764210,0.757413,0.966390,0.523086,42.3812,-71.0890,Boston,15.0,-3.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA,"[0.000775623296596168, 0.0005924976152852323, ...","[-0.006195889332312467, 0.00360256644672655, 0..."
2453,4904,0.517857,0.527475,2.454082,0.681900,1.576652,0.381375,42.3888,-71.0872,Boston,8.0,-2.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA,"[0.0011134001391010992, -0.000379057415558252,...","[-0.00943606031759845, -0.00489945641802752, -..."
2454,4162,0.465477,0.462276,1.970528,0.661715,1.627882,0.514609,40.7096,-73.9278,New York,28.0,4.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA,"[0.0007136718174012811, 0.0005144085981259512,...","[-0.011163263475166049, -0.00805429512100221, ..."
2455,4074,0.211544,0.574673,2.742072,0.794404,1.388283,0.559084,40.7035,-73.9447,New York,214.0,-4.0,/media/felipe/DATA21/datasets/pp1/images/2013/...,North America,USA,"[0.0005207238625805728, 0.00044315589572695743...","[-0.01031312623363287, -0.012640398840686582, ..."

In [12]:
%%time
from py.models.datasets import PlacePulse

pp = PlacePulse(data_df)
pp.DataPreparation(delta=cfg.DELTA, emotion=cfg.PERCEPTION_METRIC)
pp.TaskPreparation(task_type=cfg.ML_TASK)
pp.DataSplit()

print(f"Train samples: {len(pp.train_df)}")
print(f"Test samples: {len(pp.test_df)}")

Applying delta
Top max: 8.35086458651, min:5.02335188938, size: 1031
Bot max: 4.54807929686, min:0.211543520683, size: 1031
Train samples: 1546
Test samples: 516
CPU times: user 1.11 s, sys: 84.1 ms, total: 1.19 s
Wall time: 1.2 s

In [13]:
label_map = dict(zip(pp.data_df["target"], pp.data_df["label"]))
labels = list(label_map.values())
classes = list(label_map.keys())
label_map

{1: 'safety', 0: 'not safety'}

In [14]:
X_train = np.array(pp.train_df[cfg.FEATURE_VECTOR_NAME].tolist())
X_test = np.array(pp.test_df[cfg.FEATURE_VECTOR_NAME].tolist())
y_train = np.array(pp.train_df["target"].tolist())
y_test = np.array(pp.test_df["target"].tolist())
X_train.shape, X_test.shape

((1546, 8192), (516, 8192))

In [15]:
collections.Counter(y_train), collections.Counter(y_test)

(Counter({np.int64(1): 773, np.int64(0): 773}),
 Counter({np.int64(0): 258, np.int64(1): 258}))

### GridSearch

In [16]:
from py.models.classification.linear import LinearClassifier

In [17]:
model_search = LinearClassifier()

#### Train

In [18]:
%%time
results = model_search.fit_all(X_train, y_train)

============================================================
Fitting logistic_regression...
============================================================
Fitting 5 folds for each of 20 candidates, totalling 100 fits

============================================================
Fitting ridge...
============================================================
Fitting 5 folds for each of 10 candidates, totalling 50 fits

============================================================
Fitting linear_svc...
============================================================
Fitting 5 folds for each of 20 candidates, totalling 100 fits

============================================================
Fitting svm...
============================================================
Fitting 5 folds for each of 100 candidates, totalling 500 fits
CPU times: user 31.1 s, sys: 818 ms, total: 31.9 s
Wall time: 7min 26s

In [19]:
model_search.print_results()

================================================================================
GRID SEARCH RESULTS SUMMARY
================================================================================

LOGISTIC_REGRESSION:
  Best CV Score: 0.6067
  Best Parameters:
    classifier__C: 0.01
    classifier__class_weight: None
    classifier__penalty: l2

LINEAR_SVC:
  Best CV Score: 0.5931
  Best Parameters:
    classifier__C: 0.01
    classifier__class_weight: None
    classifier__loss: squared_hinge
    classifier__penalty: l2

RIDGE:
  Best CV Score: 0.5912
  Best Parameters:
    classifier__alpha: 100.0
    classifier__class_weight: None

SVM:
  Best CV Score: 0.5537
  Best Parameters:
    classifier__C: 0.1
    classifier__class_weight: None
    classifier__gamma: 0.01
    classifier__kernel: rbf

================================================================================
BEST OVERALL MODEL: LOGISTIC_REGRESSION
Best Score: 0.6067
================================================================================

In [20]:
summary_df = model_search.get_results_summary()
summary_df

,model,best_score,best_params
0,logistic_regression,0.606724,"{'classifier__C': np.float64(0.01), 'classifie..."
2,linear_svc,0.593142,"{'classifier__C': np.float64(0.01), 'classifie..."
1,ridge,0.591211,"{'classifier__alpha': np.float64(100.0), 'clas..."
3,svm,0.553716,"{'classifier__C': np.float64(0.1), 'classifier..."

#### Inference

In [21]:
from sklearn.metrics import classification_report

In [22]:
y_pred = model_search.predict(X_test) # model_name='logistic_regression')

In [23]:
clf_lr_report = classification_report(y_test, y_pred, output_dict=True)

print(classification_report(y_test, y_pred, target_names=labels))

              precision    recall  f1-score   support

      safety       0.62      0.43      0.51       258
  not safety       0.57      0.74      0.64       258

    accuracy                           0.59       516
   macro avg       0.59      0.59      0.58       516
weighted avg       0.59      0.59      0.58       516

In [24]:
confusion_matrix = pd.crosstab(
    [ label_map[k] for k in y_test ],
    [ label_map[k] for k in y_pred ],
    rownames=['Real'],
    colnames=['Prediction']
)
confusion_matrix

Prediction  not safety  safety
Real
not safety         112     146
safety              68     190

#### Saving

In [25]:
# Save grid search
model_search.save(f'{MODEL_PATH}{cfg.FEATURE_VECTOR_NAME}_model_search.pkl')

Instance saved to /media/felipe/DATA21/models/pp1/urbanvgg/2013/linear/fisher_model_search.pkl using pickle

In [26]:
# Save just the best trained model
model_search.save_best_model_only(f'{MODEL_PATH}{model_search.get_best_model_name()}_{cfg.FEATURE_VECTOR_NAME}_best_model.pkl')

Best model (logistic_regression) saved to /media/felipe/DATA21/models/pp1/urbanvgg/2013/linear/logistic_regression_fisher_best_model.pkl

#### Loading

In [27]:
loaded_search = LinearClassifier.load(f'{MODEL_PATH}{cfg.FEATURE_VECTOR_NAME}_model_search.pkl')
y_pred = loaded_search.predict(X_test)
confusion_matrix = pd.crosstab(
    [ label_map[k] for k in y_test ],
    [ label_map[k] for k in y_pred ],
    rownames=['Real'],
    colnames=['Prediction']
)
confusion_matrix

Instance loaded from /media/felipe/DATA21/models/pp1/urbanvgg/2013/linear/fisher_model_search.pkl using pickle

Prediction  not safety  safety
Real
not safety         112     146
safety              68     190

In [28]:
# Load and use the best model
best_model = LinearClassifier.load_model(f'{MODEL_PATH}{model_search.get_best_model_name()}_{cfg.FEATURE_VECTOR_NAME}_best_model.pkl')
y_pred = best_model.predict(X_test)
confusion_matrix = pd.crosstab(
    [ label_map[k] for k in y_test ],
    [ label_map[k] for k in y_pred ],
    rownames=['Real'],
    colnames=['Prediction']
)
confusion_matrix

Model loaded from /media/felipe/DATA21/models/pp1/urbanvgg/2013/linear/logistic_regression_fisher_best_model.pkl

Prediction  not safety  safety
Real
not safety         112     146
safety              68     190